apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo

resources:
  - namespace.yaml
  - web.yaml

configMapGenerator:
  - name: backend-source
    files:
      - backend/server.py
  - name: web-static
    files:
      - frontend/index.html
  - name: web-nginx
    files:
      - default.conf=frontend/nginx.conf

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
